### ISSUE TITLE
Make navigation tabs vibrant.

### ISSUE THREAD

**Issue by Visham32** [jaylenw/AngularJsTodoApp#29]
I would like to make the navigation tabs more vibrant just like the screenshot below. When a user will hover the cursor over a specific tab, the colour of the tab will change. See attached screenshot below.
![navigation](https://cloud.githubusercontent.com/assets/22685311/22287876/fda38fdc-e30d-11e6-9d3e-4752fe090fc3.png)

**Comment by jaylenw** [comment]
Sounds good. I think it would be a good addition. I look forward to the pull request regarding this feature. 

Thank you!

**Comment by Visham32** [comment]
Why is the Navigation tab "Note List" is separate compared to the other tabs?

**Comment by Visham32** [comment]
I have done the changes. It looks better now.

**Comment by jaylenw** [comment]
Ok so the reason why "Note List" is separate from compared to the other tabs is because of the bootstrap theme included in the site. http://getbootstrap.com/

You brought to me attention that I can remove the "Current List" link as it functions the same as clicking on "Note List"

**Comment by jaylenw** [comment]
If you want to make the tabs vibrant, lets leave how the tabs are now but change the color of them on hover. Possibly, to like a blue color that fits the theme.

I see you made some changes to navigation on the pull request #27 . Your pull request contains code that breaks the mobile responsiveness of the app.

***Before Your additions:***

![screenshot from 2017-01-29 17-50-21](https://cloud.githubusercontent.com/assets/6505395/22410368/2574b9e6-e64c-11e6-805e-acbf26a2497f.png)

![screenshot from 2017-01-29 17-50-45](https://cloud.githubusercontent.com/assets/6505395/22410371/2b49ffd4-e64c-11e6-9a3c-e1457253dbec.png)

![screenshot from 2017-01-29 17-50-56](https://cloud.githubusercontent.com/assets/6505395/22410372/2e9369b4-e64c-11e6-9bd6-99d4db2d17f8.png)

***After your additions:***

![screenshot from 2017-01-29 17-57-21](https://cloud.githubusercontent.com/assets/6505395/22410402/7cd21ecc-e64c-11e6-9f30-6031ff788644.png)

![screenshot from 2017-01-29 17-57-37](https://cloud.githubusercontent.com/assets/6505395/22410404/87c522f2-e64c-11e6-8dd9-894da2bcae51.png)

![screenshot from 2017-01-29 17-57-49](https://cloud.githubusercontent.com/assets/6505395/22410406/8b4eca2c-e64c-11e6-917f-80c5ed43741d.png)


I really do think the structure is fine, no need to add css classes for creating a new menu. Let's use the existing code and enhance the navigation bar with css for a color on hover.

**Comment by Visham32** [comment]
Yes i see how the mobile responsiveness breaks. Its better to keep it the same way. I will enhance the navigation bar color schemes and make a pull request.

**Comment by jaylenw** [comment]
Current master branch at this time contains commits on highlighting the buttons on the navbar and in the note areas.
