### ISSUE TITLE
Tried to register with 2 different passwords and it was successful.

### ISSUE THREAD

**Issue by Visham32** [jaylenw/AngularJsTodoApp#30]
When i registered with 2 different passwords, i got access to the 'Add a note' page. This should not happen.

**Comment by jaylenw** [comment]
Thank you for bringing this up to my attention, i can confirm that this is a problem.

**Comment by jaylenw** [comment]
commit a37f148eacdbf41cba917a5c99607e79333e1ca0 fixes this problem
