### ISSUE TITLE
Increase Spacing on Auth Page

### ISSUE THREAD

**Issue by jaylenw** [jaylenw/AngularJsTodoApp#36]
The input fields on the Auth page for a user to login and register are too close together vertically. Possibly adding spacing between the fields would make them look less compacted.

**Comment by Visham32** [comment]
I would like to work on this issue. Please confirm.

**Comment by jaylenw** [comment]
@Visham32 sounds good! thank you

**Comment by jaylenw** [comment]
pull request #39 has pulled this feature into master.
