### ISSUE TITLE
Write an install script

### ISSUE THREAD

**Issue by jaylenw** [jaylenw/AngularJsTodoApp#37]
Basically take the commands from the readme instructions on installing this project into bash script.

**Comment by alinebrito** [comment]
Hi, I can create the script. Are the commands in "Build, Testing, & Development" section, right?

**Comment by jaylenw** [comment]
Hi @alinebrito, thank you for working on the install script. I greatly appreciate it. I will look at it now and review it. If you are participating in Hacktoberfest and would like to do two more pull requests, we have issues in two similar projects that also need an install script. 
https://github.com/jaylenw/ElectronTodoApp/issues/7
https://github.com/jaylenw/IonicTodoApp/issues/16

**Comment by alinebrito** [comment]
Thank you, @jaylenw!
