### ISSUE TITLE
Clarify Authentication Page

### ISSUE THREAD

**Issue by jaylenw** [jaylenw/AngularJsTodoApp#43]
The user may be confused when trying to login or register on the authentication page. The page needs to make it clear that what the user is seeing is appropriate for what they want to do, either login or register.

**Comment by Visham32** [comment]
I would suggest to remove the Authentication title in the navigation tabs and replace it by Login/Register. This would be clear for a user what he/she is expecting when clicking on the link. Also, the word 'Authentication' seems quite complicated. I can make the changes if you approve.

**Comment by jaylenw** [comment]
Yes, I think that would be better. My only concern is I would need to think how i would change the code to properly reflect "logout" when the user is logged in and "login" when the user is not logged in. I prefer not to  have Login/Register simply replacing Authentication. I want it to show login or register depending if the user is logged in or not. With this, I also need to have register present when the user is not logged in but as well not appearing at all when the user is logged in. Do you see what I mean?

I apologize, you did mention this in #31

**Comment by Visham32** [comment]
Yes. I got your point. However, this would involve some changes in the codes. I only suggested this change because some user would be confused about this word "Authentication".

**Comment by jaylenw** [comment]
Closing as this repository will be archived.
