### ISSUE TITLE
No description of the website on any page.

### ISSUE THREAD

**Issue by Visham32** [jaylenw/AngularJsTodoApp#44]
There should be at least a title of the website for a user to know what it is about. Only on GitHub I see a clear description.

**Comment by jaylenw** [comment]
@Visham32 , were you thinking of an "About" page or description of how someone should use the app upon visiting the page? If we go with a description on the home page, I think it should only show when the user is not logged in. I don't know, we would have to brainstorm on this. What are your thoughts on this?

**Comment by Visham32** [comment]
Yes, an "About" page would have been better. However, also a brief title on the top of the homepage could have been placed. For example: "The platform where your notes are securely stored".

**Comment by jaylenw** [comment]
Perhaps a modal pop-up when clicked on the about tab would be sufficient. 

The content will be a description of what the app does, features it supports, and a link to direct users to a markup language manual.

**Comment by Visham32** [comment]
A modal popup seems interesting. However, there are some websites that lags on several computers when they have popups or sometimes it takes time to show the popup. I would recommend to keep it simple by providing the description on the "Please login or Register" page on the top itself.

**Comment by jaylenw** [comment]
Okay, I see what you mean. So we will basically have an about paragraph on top of the login/register page or would be have it on top of the home page instead? What would be better?

Below is somewhat what I would expect to be on the description. Thoughts?

"Welcome to AngularTodoJS, this is an web application that allows you to create and maintain either a to-do list or for a simple use such as note taking. This application supports plain text for notes or you can use markdown for formatting support. More information on markdown can be found here https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf. This web application is also found on Github with instructions for you to set up your own hosting of this project. The source code for the project is here https://github.com/jaylenw/AngularJsTodoApp. Feel free to contribute if you like!"

**Comment by Visham32** [comment]
The description looks good. It would fit better on the top of the login/register page. So that when a user before registering, he/she will have an idea of what the website provides.

**Comment by jaylenw** [comment]
Ok cool. Sounds good. Will you be working on this issue?

**Comment by Visham32** [comment]
@jaylenw I will try to work on this. If i am able to implement it successfully i will create a pull request on it.

**Comment by jaylenw** [comment]
Closing as this repository will be archived.
