### ISSUE TITLE
Add screenshot of the website on the README.md section on GitHub.

### ISSUE THREAD

**Issue by Visham32** [jaylenw/AngularJsTodoApp#47]
A user would more likely to contribute if he/she sees a sneak peak of the website when he/she clicks on the link to this project on GitHub.

**Comment by jaylenw** [comment]
Good suggestion, sounds good. When we are closer in finishing the other issues we will add screenshots to the repo.

**Comment by Visham32** [comment]
Good idea.

**Comment by jaylenw** [comment]
Added screenshots in repo in master branch.
