### ISSUE TITLE
Registration page fields on Mobile View needs proper spacing.

### ISSUE THREAD

**Issue by Visham32** [jaylenw/AngularJsTodoApp#48]
Using the mobile view, the fields in the registration page needs about 5 pixels of margin right and margin left. See attached screenshot.
![register - mobile view](https://cloud.githubusercontent.com/assets/22685311/24668382/c2502c4c-1977-11e7-994c-bc6775c6f64c.png)

**Comment by jaylenw** [comment]
@Visham32 . Wow thanks for catching this!

**Comment by Visham32** [comment]
You're welcome. A few CSS changes is needed.

**Comment by KaylenW** [comment]
Currently working on a branch for this fix. changes in commit here 0fe1e75f2b8ea36731c67b584a067383d88c00a9

**Comment by jaylenw** [comment]
@KaylenW  Sounds good. just send a pull request when ready.
