### ISSUE TITLE
Searching for note field in mobile view needs margin right spacing.

### ISSUE THREAD

**Issue by Visham32** [jaylenw/AngularJsTodoApp#49]
On mobile view, the search for a note field is not well aligned with the other text fields. Margin right is needed. See attached screenshot.
![searching for note field - mobile view](https://cloud.githubusercontent.com/assets/22685311/24670203/441526e6-197e-11e7-9e55-14acbb90a412.png)

**Comment by jaylenw** [comment]
Thank you for catching this as well!

**Comment by Visham32** [comment]
Welcome.

**Comment by KaylenW** [comment]
Working on a branch to fix this as well, changes are here 1226edcb6ac219b14ed2df2cdb5d9e2ee5a3461a
