### ISSUE TITLE
Viewing existing notes - Mobile View. Buttons overlap.

### ISSUE THREAD

**Issue by Visham32** [jaylenw/AngularJsTodoApp#50]
The buttons overlap on the viewing notes page. See attached screenshot.
![view notes - mobile view](https://cloud.githubusercontent.com/assets/22685311/24671430/87da0320-1982-11e7-9a20-ae013a1e1604.png)

**Comment by jaylenw** [comment]
Lol the app is really not optimized for mobile view haha. Thanks again @Visham32

**Comment by Visham32** [comment]
That's fine. @jaylenw

**Comment by KaylenW** [comment]
Implemented a fix here to fix the overlap buttons 909b475506e5fcf8cb0d4b428d50e4fd856e7243
