### ISSUE TITLE
Archive list: Buttons overlap in mobile view.

### ISSUE THREAD

**Issue by Visham32** [jaylenw/AngularJsTodoApp#52]
In the archive list as well the buttons overlap. See attached screenshot.

![17902942_1427861213931643_635530826_o](https://cloud.githubusercontent.com/assets/22685311/24941397/2bca782e-1f5b-11e7-9884-b70209a50bef.png)

**Comment by jaylenw** [comment]
Thanks @Visham32

**Comment by KaylenW** [comment]
Reference this fix in issue #50
