### ISSUE TITLE
Suggestion: Add 'eye' icon on password for a user can see the unmask password characters.

### ISSUE THREAD

**Issue by Visham32** [jaylenw/AngularJsTodoApp#53]
It could be possible for a user to see what password he/she is entering just by clicking on the 'eye' icon as shown in the attached screenshot. I have noticed that many register/login websites support this functionality.
![eye icon to show password](https://cloud.githubusercontent.com/assets/22685311/25063659/f64dd210-21fb-11e7-9001-4ac73db2a2a9.png)

**Comment by jaylenw** [comment]
Hmm, i think this would be cool. I am going to tackle the other issues before this but if you would like to make that addition that would be awesome!

Thanks!

**Comment by jaylenw** [comment]
Closing as this repository will be archived.
