### ISSUE TITLE
Remove Unneeded Variables

### ISSUE THREAD

**Issue by tmargono** [jaylenw/AngularJsTodoApp#72]
### Problem

1) There is no need to have
```
ENV userID ${userID}
ENV groupID ${groupID}
```
present inside the `Dockerfile` because `userID` and `groupID` are only used during the build process, and not when the container is actually running. Therefore, they should only be present as ARGs.

2) 
There is also no need to have 
```
 args:
    - userID=${userID}
    - groupID=${groupID}
```
present inside `docker-compose.yml` because the ARGs are already being passed to the `Dockerfile` by `build-docker.sh`. In fact, leaving these lines in the yml file and running the command `docker-compose run --service-ports notafrontend bash` given in step 4 of the README gives the pictured warning.

![nota_error](https://user-images.githubusercontent.com/23224779/89088981-dd7c2800-d34f-11ea-9ff3-0e9822a8d0ec.png)

### Solution

Remove the unneeded lines.

**Comment by jaylenw** [comment]
Closing as this repository will be archived.
